[BB-212] Project name validation
binbashar/leverage pull request #215
Opened 2023-08-24 14:56 UTC by Franr

## What?
Add validations for the project long name (coming from project.yaml).

## Why?
That name is used for folders and other stuff, that has character limitations.

## References
* `closes #212`

## Before release

Review the checklist [here](https://binbash.atlassian.net/l/cp/BthxSQ0j)

2023-08-30 22:20 UTC, angelofenoglio commented on leverage/modules/project.py
> +        raise ExitError(1, "Project name is not valid. Only lower case alphanumerics characters are allowed.")
```suggestion
        raise ExitError(1, "Project name is not valid. Only lower case alphanumeric characters are allowed.")
```
Just a small grammar correction!

2023-08-30 22:55 UTC, angelofenoglio commented on leverage/modules/project.py
> +        raise ExitError(1, "Project name is not valid. Only lower case alphanumeric characters are allowed.")
```suggestion
        raise ExitError(1, "Project name is not valid. Only lowercase alphanumeric characters are allowed.")
```
It also seems that `lowercase` altogether is the more accepted spelling: https://english.stackexchange.com/questions/59409/lowercase-lower-case-or-lower-case#59413
Sorry for making it in a different suggestion I thought it was alright but it kept bugging me 😅

2023-09-05 14:51 UTC, exequielrafaela requested changes
@Franr Cisco small comment around error message to be more explicit for the user.

2023-09-05 14:51 UTC, exequielrafaela commented on leverage/modules/project.py
> +        raise ExitError(1, "Project name is not valid. Only lowercase alphanumeric characters are allowed.")
@Franr Cisco I think we should also add "Only lowercase alphanumeric characters and hyphens '-' are allowed"
What do you think on being more explicit here?

CC: @rodriguez-matias @diego-ojeda-binbash

2023-09-05 14:54 UTC, Franr commented on leverage/modules/project.py
> +        raise ExitError(1, "Project name is not valid. Only lowercase alphanumeric characters are allowed.")
sure! done! :slightly_smiling_face:

2023-09-11 12:04 UTC, exequielrafaela approved these changes

2023-09-11 17:51 UTC, merged