195 local user
binbashar/leverage pull request #269
Opened 2024-05-25 20:30 UTC by Franr

## What?
* Describe high-level what changed as a result of these commits (i.e. in plain-english, what do these changes mean?)
* Use bullet points to be concise and to the point.

## Why?
* Provide the justifications for the changes (e.g. business case). 
* Describe why these changes were made (e.g. why do these commits fix the problem?)
* Use bullet points to be concise and to the point.

## References
* Link to any supporting github issues or helpful documentation to add some context (e.g. stackoverflow). 
* Use `closes #123`, if this PR closes a GitHub issue `#123`

## Before release

Review the checklist [here](https://binbash.atlassian.net/l/cp/BthxSQ0j)

2024-06-01 22:07 UTC, Franr commented on leverage/container.py
> -    def get_sso_code(self, container) -> str:
these were moved to the `SSOContainer` class, where they fit better

2024-06-01 22:07 UTC, Franr commented on leverage/container.py
> -    TF_SSO_ENTRYPOINT = "/root/scripts/aws-sso/aws-sso-entrypoint.sh"
the SSO script was unused, is part of the CLI (in python) already

2024-06-01 22:07 UTC, Franr commented on leverage/scripts/aws-mfa/aws-mfa-entrypoint.sh
These were moved from the toolbox into the CLI, and are mounted into the container when we run commands.
That give us a better control and an easier way to introduce modifications over them.

2024-06-01 22:16 UTC, Franr commented on leverage/modules/terraform.py
> -    with LiveContainer(tf) as container:
copying ssh keys and changing permissions is not required anymore, given now the user of the container and the host matches (thus permissions matches!)

2024-06-03 18:43 UTC, diego-ojeda-binbash requested changes

2024-06-03 18:43 UTC, diego-ojeda-binbash commented on leverage/containers/kubectl.py
> +    KUBECTL_CONFIG_PATH = Path("/home/leverage/.kube")
Please replace 'leverage' with the constant that defines that.

2024-06-08 14:02 UTC, Franr commented on leverage/containers/kubectl.py
> +    KUBECTL_CONFIG_PATH = Path("/home/leverage/.kube")
done :ok_hand:

2024-09-08 19:30 UTC, Franr commented on Makefile
> +LEVERAGE_IMAGE_TAG     := 1.2.7-0.1.14
actually we now need the last toolbox image (0.1.19) that support the custom home folder

2024-10-07 18:10 UTC, angelofenoglio approved these changes

2024-10-07 18:21 UTC, juanmatias approved these changes

2024-10-07 18:55 UTC, merged